BIN         :=  bin

SUBDIRS := bar foo 

.PHONY: all $(SUBDIRS) 

all: $(BIN) $(SUBDIRS) main test_mvs
$(SUBDIRS):
	$(MAKE) -C $@

default: $(BIN) main

main:
	gcc -Lfoo/lib -Wall -o bin/main main.c -lfoo -lpthread

test_mvs:
	mv bar/output bin/tmp
	ar -rc bin/libmvs.a bin/tmp/output/foo.o
	gcc -Lbin/ -Wall -o bin/main_mvs main.c -lmvs -lpthread

$(BIN):
	mkdir $@
	mkdir bin/tmp

clean:
	$(MAKE) -C foo clean
	$(MAKE) -C bar clean
	rm -rf *.o *.out
	rm -rf bin/
	rm -rf .coderrect
