#!/usr/bin/perl

use strict;
use warnings;


#
# main($awsKeyId, $awsSecretkey, $region)
#
$ENV{'AWS_ACCESS_KEY_ID'} = $ARGV[0];
$ENV{'AWS_SECRET_ACCESS_KEY'} = $ARGV[1];
$ENV{'AWS_DEFAULT_REGION'} = $ARGV[2];

print `aws s3 ls s3://internal-installer-pkg`;


__END__
