[package]
name = "jet-cli"
version = "0.2.0"
edition = "2018"

[dependencies]
structopt = "0.3"
bytemuck = "1.7"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pyth-client = "0.2"
anchor-lang = "0.18.2"
anchor-client = "0.18.2"
anchor-spl = "0.18.2"
solana-account-decoder = "1.7"
solana-transaction-status = "1.7"
toml = "0.5"
shellexpand = "2.1"

jet = { path = "../../programs/jet" }
jet-math = { version = "1", package = "jet-proto-math" }