#!/bin/bash

printHelp() {
  cat << EOF
Runs Coderrect Scan.

Usage:
  docker-coderrect [options] build-command

  -h            
    Print this message
  -i,--image    
    Run container from this image, default is coderrect base image

Examples:
  1. Scan the source code in latest image
  \$ docker-coderrect gcc hello.c

  2. Scan the source code in specified image
  \$ docker-coderrect -i myimage make
EOF
}

defaultImage=coderrect/coderrect
imageName=
buildCommand=()
while (( "$#" )); do
    case "$1" in
        -h|--help)
            printHelp
            exit 3
            ;;
        -i|--image)
            imageName=$2
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            buildCommand+=("$1")
            shift
            ;;
    esac
done

# Verify parameters
length=${#buildCommand[@]}
if (( length < 1 )); then 
    echo "build command not provided"
    printHelp
    exit 1;
fi

if [ -z "$imageName" ] ; then
    # Get default version
    dirPath="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
    coderrectPath=$(dirname $dirPath)
    # echo "$dirPath, $coderrectPath"

    # We need parse the string like following
    # package develop build 1612152257
    # package (hpc) 0.9.2 build 1610730537
    versionPath=$coderrectPath/VERSION
    if [ -f "${versionPath}" ]; then
        versionFileContent=$(cat $versionPath)
    fi
    IFS=', ' read -r -a versionTokenList <<< "$versionFileContent"
    # echo "Detected Coderrect package name: ${versionTokenList[1]}"
    if [ "${versionTokenList[1]}" == "develop" ] ; then
        imageName="$defaultImage:linux-develop"
    elif [ "${versionTokenList[1]}" == "(hpc)" ] ; then
        imageName="$defaultImage:linux-hpc-${versionTokenList[2]}"
    elif [ "${versionTokenList[1]}" == "(system)" ] ; then
        imageName="$defaultImage:linux-system-${versionTokenList[2]}"
    else 
        imageName=$defaultImage
    fi 
fi 

echo "The docker image is: $imageName"

docker run --rm \
    --user=$(id -u):$(id -g) \
    -v $(pwd):/src \
    -it $imageName \
    coderrect ${buildCommand[*]}
