FROM centos:7.0.1406 as base

# install python3,pytest
RUN yum update -y nss curl libcurl; \
    yum -y install python3 python3-pip

RUN pip3 install pytest pytest-repeat pytest-timeout pytest-xdist pyyaml tqdm

ENV TEST_ON_AWS_REPORTDIR=/installer/build/test/report

# Install dependencies
RUN yum -y install autoconf automake cmake git make jq build-essential ca-certificates wget vim gcc unzip mpich; \
    yum -y install gcc-c++ gcc-gfortran libevent-devel clang

ENV C_INCLUDE_PATH=/usr/lib/gcc/x86_64-redhat-linux/4.8.2/include:$C_INCLUDE_PATH

# Install libomp.so
RUN yum -y install centos-release-scl-rh; \
    yum -y install llvm-toolset-7.0-libomp
RUN cp /opt/rh/llvm-toolset-7.0/root/usr/lib64/libomp.so /usr/lib/

# Install jq
RUN yum -y install epel-release; \
    yum -y install jq
