FROM ubuntu:16.04

# Install dependencies
RUN apt update; \
    apt install -y curl python3 make gcc g++ 

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; \
    python3 get-pip.py; \
    rm -f get-pip.py

RUN pip3 install pytest

ENV CODERRECT_HOME=/compat_test/coderrect-linux
ENV PATH=$CODERRECT_HOME/bin:$PATH
