[package]
name = "jet"
version = "0.2.0"
description = "Jet Lending Program"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "jet"
doctest = false

[features]
no-entrypoint = []
no-idl = []
devnet = ["anchor-spl/devnet"]
cpi = []
default = ["cpi"]

[dependencies]
anchor-lang = "0.18.2"
anchor-spl = { version = "0.18.2", features = ["dex"] }
solana-program = "1.7"
thiserror = "1.0"
bytemuck = { version = "1.7", features = ["derive"] }
pyth-client = "0.2"
static_assertions = "1.1.0"
bitflags = "1.3"

jet-math = { version = "1", package = "jet-proto-math" }
jet-proc-macros = { version = "1", package = "jet-proto-proc-macros" }