name: Build and push llvm-prebuilt image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build llvm-prebuilt image
        run: |
          make build-llvm-prebuilt-image

      - name: Push llvm-prebuilt image
        run: |
          make push-llvm-prebuilt-image
