name: Build X-Ray

# Avoid having multiple builds simultaneously.
concurrency:
  group: build-x-ray

on:
  push:
    branches:
      - main

jobs:
  build-container:
    runs-on: self-hosted
    env:
      X_RAY_IMAGE: x-ray-ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Remove existing GitHub registry login
        run: |
          docker logout ghcr.io

      - name: Build container image
        run: |
          make build-container-image

      - name: Run container E2E tests
        run: |
          make run-container-e2e

  build-native:
    runs-on: self-hosted
    env:
      BUILD_DIR: ${{ github.workspace }}/build
      LLVM_PREBUILT_PATH: ${{ github.workspace }}/build/llvm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Remove existing GitHub registry login
        run: |
          docker logout ghcr.io

      - name: Extract LLVM prebuilt binaries
        run: |
          make extract-llvm

      - name: Build and install x-ray binaries
        run: |
          make -j build-x-ray
          make install

      - name: Run E2E tests
        run: |
          make run-native-e2e
