name: X-ray CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log into DigitalOcean container registry
        run: doctl registry login --expiry-seconds 600

      - name: Build Docker image
        run: |
          make build-image

      - name: Run Docker container
        run: |
          docker run x-ray:latest

      - name: Clean up containers
        if: always()
        run: |
          docker ps --all --quiet --filter ancestor=x-ray:latest | xargs -r docker stop
          docker ps --all --quiet --filter ancestor=x-ray:latest | xargs -r docker rm
