name: X-ray CI

on:
  push:
    branches:
      - main
      - llvm-src
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t x-ray:latest .

      - name: Run Docker container
        run: docker run -d --name x-ray-container x-ray:latest

      - name: Verify Docker container is running
        run: docker ps | grep x-ray-container
